name: Test Action

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v4

    - name: 24f2004808@ds.study.iitm.ac.in
      run: echo "Hello, world!"

    - name: List files
      run: ls -la

    - name: prime-cache-9abf99d
      uses: actions/cache@v4
      with:
        key: cache-9abf99d
        path: ~/.cache  # Caches a generic folder (works for demo)

